import { getLayout } from '@/components'
import { CountUsers } from '@/views/public-page/ui/CountUsers'
import { Posts } from '@/views/public-page/ui/Posts'
import Head from 'next/head'

export const getStaticProps = async () => {
  const res = await fetch('https://inctagram.work/api/v1/public-posts/all')
  const res2 = await fetch('https://inctagram.work/api/v1/public-user')
  const posts = await res.json()
  const countUsers = await res2.json()

  return {
    props: {
      countUsers,
      posts,
    },
    //если написали revalidate, при новом запросе страницы и когда прошло 60 сек
    //вызывается функция getStaticProps нэкстом и страница проревалидируется и перезапишется с новыми данными
    revalidate: 60,
  }
}

type Props = {
  countUsers: any
  posts: any
}

export default function Home({ countUsers, posts }: Props) {
  console.log(posts)
  console.log(countUsers)

  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link
          href={'/apple-touch-icon.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'apple-touch-icon'}
          sizes={'180x180'}
        />
        <link
          href={'/apple-touch-icon-dark.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'apple-touch-icon'}
          sizes={'180x180'}
        />
        <link
          href={'/favicon-32x32.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
          sizes={'32x32'}
          type={'image/png'}
        />
        <link
          href={'/favicon-dark-32x32.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'icon'}
          sizes={'32x32'}
          type={'image/png'}
        />
        <link
          href={'/favicon-16x16.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
          sizes={'16x16'}
          type={'image/png'}
        />
        <link
          href={'/favicon-dark-16x16.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'icon'}
          sizes={'16x16'}
          type={'image/png'}
        />
        <link href={'/site.webmanifest'} rel={'manifest'} />
        <link
          href={'/favicon.ico?v=2'}
          id={'favicon'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
        />
        <link href={'/favicon-dark.ico?v=2'} media={'(prefers-color-scheme: light)'} rel={'icon'} />
      </Head>
      <main className={'container'}>
        <CountUsers countUsers={countUsers.totalCount} />
        <div>
          <Posts posts={posts} />
        </div>
      </main>
    </>
  )
}

Home.getLayout = getLayout
