import { getLayout } from '@/components'
import { PostsData, PostsRes } from '@/shared/types/public-page/Posts'
import { CountUsersRes } from '@/shared/types/public-page/PublicPage'
import { CountUsers } from '@/views/public-page/ui/CountUsers'
import { Posts } from '@/views/public-page/ui/Posts'
import Head from 'next/head'

export const getStaticProps = async () => {
  const postsResponse = await fetch('https://gateway.inctagram.world/api/v1/posts')
  const countUsersResponse = await fetch(
    'https://gateway.inctagram.world/api/v1/profile/user-count'
  )

  const postsData: PostsRes = await postsResponse.json()
  const countUsers: CountUsersRes = await countUsersResponse.json()

  return {
    props: {
      countUsers: countUsers.count,
      posts: postsData.posts,
    },
    revalidate: 60,
  }
}

type Props = {
  countUsers: number
  posts: PostsData
}

export default function Home({ countUsers, posts }: Props) {
  console.log(posts)

  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link
          href={'/apple-touch-icon.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'apple-touch-icon'}
          sizes={'180x180'}
        />
        <link
          href={'/apple-touch-icon-dark.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'apple-touch-icon'}
          sizes={'180x180'}
        />
        <link
          href={'/favicon-32x32.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
          sizes={'32x32'}
          type={'image/png'}
        />
        <link
          href={'/favicon-dark-32x32.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'icon'}
          sizes={'32x32'}
          type={'image/png'}
        />
        <link
          href={'/favicon-16x16.png?v=2'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
          sizes={'16x16'}
          type={'image/png'}
        />
        <link
          href={'/favicon-dark-16x16.png?v=2'}
          media={'(prefers-color-scheme: light)'}
          rel={'icon'}
          sizes={'16x16'}
          type={'image/png'}
        />
        <link href={'/site.webmanifest'} rel={'manifest'} />
        <link
          href={'/favicon.ico?v=2'}
          id={'favicon'}
          media={'(prefers-color-scheme: dark)'}
          rel={'icon'}
        />
        <link href={'/favicon-dark.ico?v=2'} media={'(prefers-color-scheme: light)'} rel={'icon'} />
      </Head>
      <main className={'wrapper container'}>
        <CountUsers countUsers={countUsers} />
        <div>
          <Posts posts={posts} />
        </div>
      </main>
    </>
  )
}

Home.getLayout = getLayout
