import { ReactNode } from 'react'

import {
  ArrowBackOutlineIcon,
  ArrowForwardOutlineIcon,
  ArrowIosBackIcon,
  ArrowIosBackOutlineIcon,
  ArrowIosDownOutlineIcon,
  ArrowIosForwardIcon,
  ArrowIosForwardOutlineIcon,
  ArrowIosUpIcon,
  BellIcon,
  BellOutlineIcon,
  BlockIcon,
  BookmarkIcon,
  BookmarkOutlineIcon,
  BraveIcon,
  CalendarIcon,
  CalendarOutlineIcon,
  CheckmarkOutlineIcon,
  CloseIcon,
  CloseOutlineIcon,
  ColorPaletteOutlineIcon,
  CopyIcon,
  CopyOutlineIcon,
  CreditCardIconIcon,
  CreditCardOutlineIcon,
  DoneAllOutlineIcon,
  EditIcon,
  EditOutlineIcon,
  EmailIcon,
  EmailOutlineIcon,
  ExpandIcon,
  ExpandOutlineIcon,
  EyeIcon,
  EyeOffIcon,
  EyeOffOutlineIcon,
  EyeOutlineIcon,
  FacebookIcon,
  FirefoxIcon,
  FlagRussiaIcon,
  FlagUnitedKingdomIcon,
  GithubIcon,
  GoogleIcon,
  HeartIcon,
  HeartOutlineIcon,
  HomeIcon,
  HomeOutlineIcon,
  ImageIcon,
  ImageOutlineIcon,
  LayersIcon,
  LayersOutlineIcon,
  LogOutIcon,
  LogOutOutlineIcon,
  MSEdgeIcon,
  MSExplorerIcon,
  MaximizeIcon,
  MaximizeOutlineIcon,
  MenuOutlineIcon,
  MessageCircleIcon,
  MessageCircleOutlineIcon,
  MicIcon,
  MicOutlineIcon,
  MoreHorizontalIcon,
  MoreHorizontalOutlineIcon,
  OperaIcon,
  PaidIcon,
  PaperPlaneIcon,
  PaperPlaneOutlineIcon,
  PauseCircleIcon,
  PauseCircleOutlineIcon,
  PaypalIcon,
  PersonAddIcon,
  PersonAddOutlineIcon,
  PersonIcon,
  PersonOutlineIcon,
  PersonRemoveIcon,
  PersonRemoveOutlineIcon,
  PinIcon,
  PinOutlineIcon,
  PlayCircleIcon,
  PlayCircleOutlineIcon,
  PlusCircleIcon,
  PlusCircleOutlineIcon,
  PlusSquareIcon,
  PlusSquareOutlineIcon,
  RadioButtonCheckedIcon,
  RadioButtonUncheckedIcon,
  RecaptchaIcon,
  SafariIcon,
  SearchIcon,
  SearchOutlineIcon,
  SettingsIcon,
  SettingsOutlineIcon,
  StripeIcon,
  TrashIcon,
  TrashOutlineIcon,
  TrendingUpIcon,
  TrendingUpOutlineIcon,
  UcBrowserIcon,
  YandexIcon,
} from '@/components/ui/icons'

import s from './Iconography.module.scss'

export type Icon = {
  component: ReactNode
  name: string
}

export const iconsList: Icon[] = [
  { component: <ArrowBackOutlineIcon className={s.icon} />, name: 'Arrow Back Outline' },
  { component: <ArrowForwardOutlineIcon className={s.icon} />, name: 'Arrow Forward Outline' },
  { component: <ArrowIosBackIcon className={s.icon} />, name: 'Arrow Ios Back' },
  { component: <ArrowIosBackOutlineIcon className={s.icon} />, name: 'Arrow Ios Back Outline' },
  { component: <ArrowIosDownOutlineIcon className={s.icon} />, name: 'Arrow Ios Down Outline' },
  { component: <ArrowIosForwardIcon className={s.icon} />, name: 'Arrow Ios Forward' },
  {
    component: <ArrowIosForwardOutlineIcon className={s.icon} />,
    name: 'Arrow Ios Forward Outline',
  },
  { component: <ArrowIosUpIcon className={s.icon} />, name: 'Arrow Ios Up' },
  { component: <BlockIcon className={s.icon} />, name: 'Block' },
  { component: <BookmarkIcon className={s.icon} />, name: 'Bookmark' },
  { component: <BookmarkOutlineIcon className={s.icon} />, name: 'Bookmark Outline' },
  { component: <CalendarIcon className={s.icon} />, name: 'Calendar' },
  { component: <CalendarOutlineIcon className={s.icon} />, name: 'Calendar Outline' },
  { component: <CheckmarkOutlineIcon className={s.icon} />, name: 'Checkmark Outline' },
  { component: <CloseIcon className={s.icon} />, name: 'Close' },
  { component: <CloseOutlineIcon className={s.icon} />, name: 'Close Outline' },
  { component: <ColorPaletteOutlineIcon className={s.icon} />, name: 'Color Palette Outline' },
  { component: <CopyIcon className={s.icon} />, name: 'Copy' },
  { component: <CopyOutlineIcon className={s.icon} />, name: 'Copy Outline' },
  { component: <CreditCardIconIcon className={s.icon} />, name: 'Credit Card' },
  { component: <CreditCardOutlineIcon className={s.icon} />, name: 'Credit Card Outline' },
  { component: <DoneAllOutlineIcon className={s.icon} />, name: 'Done All Outline' },
  { component: <EditIcon className={s.icon} />, name: 'Edit' },
  { component: <EditOutlineIcon className={s.icon} />, name: 'Edit Outline' },
  { component: <EmailIcon className={s.icon} />, name: 'Email' },
  { component: <EmailOutlineIcon className={s.icon} />, name: 'Email Outline' },
  { component: <ExpandIcon className={s.icon} />, name: 'Expand' },
  { component: <ExpandOutlineIcon className={s.icon} />, name: 'Expand Outline' },
  { component: <EyeIcon className={s.icon} />, name: 'Eye' },
  { component: <EyeOffIcon className={s.icon} />, name: 'Eye Off' },
  { component: <EyeOffOutlineIcon className={s.icon} />, name: 'EyeOff Outline' },
  { component: <EyeOutlineIcon className={s.icon} />, name: 'Eye Outline' },
  { component: <BellIcon className={s.icon} />, name: 'Bell' },
  { component: <BellOutlineIcon className={s.icon} />, name: ' Bell Outline' },
  { component: <HeartIcon className={s.icon} />, name: 'Heart' },
  { component: <HeartOutlineIcon className={s.icon} />, name: 'Heart Outline' },
  { component: <HomeIcon className={s.icon} />, name: 'Home' },
  { component: <HomeOutlineIcon className={s.icon} />, name: 'Home Outline' },
  { component: <ImageIcon className={s.icon} />, name: 'Image' },
  { component: <ImageOutlineIcon className={s.icon} />, name: 'Image Outline' },
  { component: <LayersIcon className={s.icon} />, name: 'Layers' },
  { component: <LayersOutlineIcon className={s.icon} />, name: 'Layers Outline' },
  { component: <LogOutIcon className={s.icon} />, name: 'Log Out' },
  { component: <LogOutOutlineIcon className={s.icon} />, name: 'Log Out Outline' },
  { component: <MaximizeIcon className={s.icon} />, name: 'Maximize' },
  { component: <MaximizeOutlineIcon className={s.icon} />, name: 'Maximize Outline' },
  { component: <MenuOutlineIcon className={s.icon} />, name: 'Menu Outline' },
  { component: <MessageCircleIcon className={s.icon} />, name: 'Message Circle' },
  { component: <MessageCircleOutlineIcon className={s.icon} />, name: 'Message Circle Outline' },
  { component: <MicIcon className={s.icon} />, name: 'Mic' },
  { component: <MicOutlineIcon className={s.icon} />, name: 'Mic Outline' },
  { component: <MoreHorizontalIcon className={s.icon} />, name: 'More Horizontal' },
  {
    component: <MoreHorizontalOutlineIcon className={s.icon} />,
    name: 'More Horizontal Outline',
  },
  { component: <PaperPlaneIcon className={s.icon} />, name: 'Paper Plane' },
  { component: <PaperPlaneOutlineIcon className={s.icon} />, name: 'Paper Plane Outline' },
  { component: <PauseCircleIcon className={s.icon} />, name: 'Pause Circle' },
  { component: <PauseCircleOutlineIcon className={s.icon} />, name: 'Pause Circle Outline' },
  { component: <PersonAddIcon className={s.icon} />, name: 'Person Add' },
  { component: <PersonAddOutlineIcon className={s.icon} />, name: 'Person Add Outline' },
  { component: <PersonIcon className={s.icon} />, name: 'Person' },
  { component: <PersonOutlineIcon className={s.icon} />, name: 'Person Outline' },
  { component: <PersonRemoveIcon className={s.icon} />, name: 'Person Remove' },
  { component: <PersonRemoveOutlineIcon className={s.icon} />, name: 'Person Remove Outline' },
  { component: <PinIcon className={s.icon} />, name: 'Pin' },
  { component: <PinOutlineIcon className={s.icon} />, name: 'Pin Outline' },
  { component: <PlayCircleIcon className={s.icon} />, name: 'Play Circle' },
  { component: <PlayCircleOutlineIcon className={s.icon} />, name: 'Play Circle Outline' },
  { component: <PlusCircleIcon className={s.icon} />, name: 'Plus Circle' },
  { component: <PlusCircleOutlineIcon className={s.icon} />, name: 'Plus Circle Outline' },
  { component: <PlusSquareIcon className={s.icon} />, name: 'Plus Square' },
  { component: <PlusSquareOutlineIcon className={s.icon} />, name: 'Plus Square Outline' },
  { component: <RadioButtonCheckedIcon className={s.icon} />, name: 'Radio Button Checked' },
  { component: <RadioButtonUncheckedIcon className={s.icon} />, name: 'Radio Button Unchecked' },

  { component: <SearchIcon className={s.icon} />, name: 'Search' },
  { component: <SearchOutlineIcon className={s.icon} />, name: 'Search Outline' },
  { component: <SettingsIcon className={s.icon} />, name: 'Settings' },
  { component: <SettingsOutlineIcon className={s.icon} />, name: 'Settings Outline' },
  { component: <TrashIcon className={s.icon} />, name: 'Trash' },
  { component: <TrashOutlineIcon className={s.icon} />, name: 'Trash Outline' },
  { component: <TrendingUpIcon className={s.icon} />, name: 'Trending Up' },
  { component: <TrendingUpOutlineIcon className={s.icon} />, name: 'Trending Up Outline' },
  { component: <RecaptchaIcon className={s.icon} />, name: 'Recaptcha' },
]

export const browserIconsList: Icon[] = [
  { component: <BraveIcon className={s.icon} />, name: 'Brave' },
  { component: <MSExplorerIcon className={s.icon} />, name: 'MS Explorer' },
  { component: <FirefoxIcon className={s.icon} />, name: 'Firefox' },
  { component: <MSEdgeIcon className={s.icon} />, name: 'MS Edge' },
  { component: <OperaIcon className={s.icon} />, name: 'Opera' },
  { component: <SafariIcon className={s.icon} />, name: 'Safari' },
  { component: <UcBrowserIcon className={s.icon} />, name: 'Uc' },
  { component: <YandexIcon className={s.icon} />, name: 'Yandex' },
]

export const flagsIconsList: Icon[] = [
  { component: <FlagRussiaIcon className={s.icon} />, name: 'Russia' },
  { component: <FlagUnitedKingdomIcon className={s.icon} />, name: 'United Kingdom' },
]

export const paymentsIconsList: Icon[] = [
  { component: <PaidIcon className={s.icon} />, name: 'Paid' },
  { component: <PaypalIcon className={s.icon} />, name: 'Paypal' },
  { component: <StripeIcon className={s.icon} />, name: 'Stripe' },
]

export const socialNetworksIconsList: Icon[] = [
  { component: <FacebookIcon className={s.icon} />, name: 'Facebook' },
  { component: <GithubIcon className={s.icon} />, name: 'Github' },
  { component: <GoogleIcon className={s.icon} />, name: 'Google' },
]
