export enum Paths {
  create = '/create',
  createPassword = '/auth/create-password',
  favourites = '/favourites',
  forgotPassword = '/auth/forgot-password',
  home = '/',
  logIn = '/auth/sign-in',
  messages = '/messages',
  passwordRecovery = '/auth/password-recovery',
  privacyPolicy = '/docs/privacy-policy',
  profile = '/profile',
  profileSettings = '/profile-settings',
  profileSettings_account = '/profile-settings/account',
  profileSettings_devices = '/profile-settings/devices',
  profileSettings_general = '/profile-settings/general',
  profileSettings_payments = '/profile-settings/payments',
  search = '/search',
  signUp = '/auth/sign-up',
  statistics = '/statistics',
  termsOfService = '/docs/terms-of-service',
}
